version: '3.8'

services:
  icecast:
    image: moul/icecast
    container_name: icecast-server
    ports:
      - "8000:8000"             # Expose Icecast on port 8000
    environment:
      - ICECAST_ADMIN_PASSWORD=admin
      - ICECAST_SOURCE_PASSWORD=sourcepassword
      - ICECAST_RELAY_PASSWORD=relaypassword
      - ICECAST_PASSWORD=adminpassword
    volumes:
      - ./icecast/icecast.xml:/etc/icecast.xml   # Custom Icecast configuration
    networks:
      - media-network
    restart: unless-stopped

  obplayer:
    build:
      context: ./obplayer       # Build using Dockerfile in obplayer directory
    container_name: ob-player
    ports:
      - "23233:23233"           # Expose obplayer admin interface
    networks:
      - media-network
    restart: unless-stopped
    depends_on:
      - icecast                 # Start Icecast before obplayer
      
  mysql-db:
    container_name: mysql-db
    restart: always
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: obdb
      MYSQL_USER: obsuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - media-network
      
  ob-server:
    restart: always
    container_name: ob-server
    depends_on:
      - mysql-db
    build:
      context: ./observer
    ports:
      - "8080:80"
    networks:
      - media-network

volumes:
  mysql-data:
      
      
networks:
  media-network:
    driver: bridge
